---
version: "3"

services:
  x-sl:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: x-sl
    hostname: yourhostname
    volumes:
      - $PWD/db/:/etc/x-sl/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "true"
    tty: true
    network_mode: host
    restart: unless-stopped
